#!/usr/bin/env python3
"""Generate urdf/spyder_quad.urdf — the 12-DoF quad in the portable format.

The kinematic tree (joint origins/axes/limits, the baked sprawl stance) comes from
spyder_params; the link inertials are read back out of the COMPILED MuJoCo model
(mass/com/inertia that MuJoCo solved from the collision geoms), so the URDF is
physically consistent with what we train on — the same handoff a robotics team
ships to Isaac / Gazebo. Re-imports into MuJoCo to confirm the round-trip.

    ./mujoco-env/bin/python scripts/make_quad_urdf.py
"""

from __future__ import annotations

import math
import os
import sys

import mujoco
import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import spyder_params as P
import make_quad_xml as Q

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MJCF = os.path.join(ROOT, "models", "spyder_quad.xml")
OUT = os.path.join(ROOT, "urdf", "spyder_quad.urdf")


def _mat2rpy(r):  # URDF fixed-axis roll-pitch-yaw: R = Rz(yaw) Ry(pitch) Rx(roll)
    pitch = math.atan2(-r[2, 0], math.hypot(r[0, 0], r[1, 0]))
    roll = math.atan2(r[2, 1], r[2, 2])
    yaw = math.atan2(r[1, 0], r[0, 0])
    return roll, pitch, yaw


def _inertial(model, body_name) -> str:
    b = model.body(body_name)
    m = float(b.mass[0])
    cx, cy, cz = b.ipos
    mat = np.zeros(9)
    mujoco.mju_quat2Mat(mat, b.iquat)
    roll, pitch, yaw = _mat2rpy(mat.reshape(3, 3))
    ix, iy, iz = b.inertia  # principal moments in the inertial frame
    return (f'    <inertial><origin xyz="{cx:.5f} {cy:.5f} {cz:.5f}" rpy="{roll:.5f} {pitch:.5f} {yaw:.5f}"/>'
            f'<mass value="{m:.5f}"/>'
            f'<inertia ixx="{ix:.6f}" iyy="{iy:.6f}" izz="{iz:.6f}" ixy="0" ixz="0" iyz="0"/></inertial>\n')


def _link(name, mesh, model, collision) -> str:
    return (f'  <link name="{name}">\n'
            f'{_inertial(model, name)}'
            f'    <visual><geometry><mesh filename="{mesh}.stl"/></geometry></visual>\n'
            f'{collision}'
            f'  </link>\n')


def build(model) -> str:
    h2 = Q.TRUNK_BOX
    hb = Q.HIP_BOX
    trunk_col = (f'    <collision><geometry><box size="{2*h2[0]:.4f} {2*h2[1]:.4f} {2*h2[2]:.4f}"/></geometry></collision>\n')
    hip_col = (f'    <collision><geometry><box size="{2*hb[0]:.4f} {2*hb[1]:.4f} {2*hb[2]:.4f}"/></geometry></collision>\n')

    def box_col(half, length):
        return (f'    <collision><origin xyz="0 0 {-length/2:.4f}"/>'
                f'<geometry><box size="{2*half[0]:.4f} {2*half[1]:.4f} {2*half[2]:.4f}"/></geometry></collision>\n')

    out = ['<?xml version="1.0"?>\n',
           '<!-- FULL 12-DoF spyder, generated by scripts/make_quad_urdf.py. -->\n',
           '<robot name="spyder_quad">\n',
           # fusestatic=false: MuJoCo would otherwise fuse the jointless root link
           # (trunk) into the world on import and silently drop its inertial,
           # which would make the round-trip mass check below read legs-only.
           '  <mujoco><compiler meshdir="../models/assets" discardvisual="false" balanceinertia="true" fusestatic="false"/></mujoco>\n',
           _link("trunk", "trunk", model, trunk_col)]

    for name, sx, sy in P.LEGS:
        haa, hfe, kfe = P.default_angles(sx, sy)
        foot_col = (f'    <collision><origin xyz="0 0 {-P.SHANK_LEN:.4f}"/>'
                    f'<geometry><sphere radius="{P.FOOT_R}"/></geometry></collision>\n')
        out += [
            _link(f"{name}_hip", "hip", model, hip_col),
            _link(f"{name}_thigh", "thigh", model, box_col(Q.THIGH_BOX, P.THIGH_LEN)),
            _link(f"{name}_shank", "shank", model, box_col(Q.SHANK_BOX, P.SHANK_LEN) + foot_col),
            f'  <joint name="{name}_haa" type="revolute">\n'
            f'    <parent link="trunk"/><child link="{name}_hip"/>\n'
            f'    <origin xyz="{P.HIP_X*sx:.4f} {P.HIP_Y*sy:.4f} {P.HIP_Z:.4f}" rpy="{haa:.5f} 0 0"/>\n'
            f'    <axis xyz="1 0 0"/><limit lower="{math.radians(P.HAA_RANGE_DEG[0]):.4f}" upper="{math.radians(P.HAA_RANGE_DEG[1]):.4f}" effort="80" velocity="12"/>\n  </joint>\n',
            f'  <joint name="{name}_hfe" type="revolute">\n'
            f'    <parent link="{name}_hip"/><child link="{name}_thigh"/>\n'
            f'    <origin xyz="0 {P.HIP_LEN*sy:.4f} 0" rpy="0 {hfe:.5f} 0"/>\n'
            f'    <axis xyz="0 1 0"/><limit lower="{math.radians(P.HFE_RANGE_DEG[0]):.4f}" upper="{math.radians(P.HFE_RANGE_DEG[1]):.4f}" effort="80" velocity="12"/>\n  </joint>\n',
            f'  <joint name="{name}_kfe" type="revolute">\n'
            f'    <parent link="{name}_thigh"/><child link="{name}_shank"/>\n'
            f'    <origin xyz="0 0 {-P.THIGH_LEN:.4f}" rpy="0 {kfe:.5f} 0"/>\n'
            f'    <axis xyz="0 1 0"/><limit lower="{math.radians(P.KFE_RANGE_DEG[0]):.4f}" upper="{math.radians(P.KFE_RANGE_DEG[1]):.4f}" effort="80" velocity="12"/>\n  </joint>\n',
        ]
    out.append('</robot>\n')
    return "".join(out)


def main():
    model = mujoco.MjModel.from_xml_path(MJCF)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write(build(model))
    # round-trip: re-import the URDF into MuJoCo
    rt = mujoco.MjModel.from_xml_path(OUT)
    print(f"wrote {OUT}")
    print(f"re-imported: bodies={rt.nbody - 1}  joints={rt.njnt}  meshes={rt.nmesh}  mass={rt.body_mass.sum():.2f} kg")

    import imageio
    d = mujoco.MjData(rt)
    mujoco.mj_forward(rt, d)
    cam = mujoco.MjvCamera()
    cam.distance, cam.azimuth, cam.elevation = 2.4, 135, -15
    cam.lookat[:] = (0, 0, 0.25)
    r = mujoco.Renderer(rt, 480, 480)
    r.update_scene(d, cam)
    imageio.imwrite("/tmp/urdf_quad.png", r.render())
    print("rendered /tmp/urdf_quad.png")


if __name__ == "__main__":
    main()
