#!/usr/bin/env python3
"""Generate a FULL URDF of the 8-DoF spyder (the whole Ant skeleton).

This is the Phase 3 "see the universal format" exercise: translate every body /
joint / geom of models/spyder.xml into URDF. Two format gaps to bridge:
  * URDF has no capsule -> leg capsules become cylinders (same radius/length).
  * URDF has no free joint -> the torso welds to the world on import (it floats).

Cylinders in URDF lie along local +Z and are centred on the link origin, so for
a segment that starts at the joint and points along `seg`, we offset by seg/2 and
rotate +Z onto `seg`. All spyder segments are horizontal, so the rotation is
rpy = (0, 90deg, atan2(dy, dx)).

Usage:
    ./mujoco-env/bin/python scripts/make_urdf.py
"""

from __future__ import annotations

import math
import os

# Per leg: (id, hip_pos, thigh_seg, shin_seg, hip_axis, ankle_axis, hip_range, ankle_range)
# Pulled straight from models/spyder.xml (fromto vectors + joint axes/ranges).
LEGS = [
    ("1", (0.2, 0.2, 0), (0.2, 0.2, 0), (0.4, 0.4, 0), (0, 0, 1), (-1, 1, 0), (-30, 30), (30, 70)),
    ("2", (-0.2, 0.2, 0), (-0.2, 0.2, 0), (-0.4, 0.4, 0), (0, 0, 1), (1, 1, 0), (-30, 30), (-70, -30)),
    ("3", (-0.2, -0.2, 0), (-0.2, -0.2, 0), (-0.4, -0.4, 0), (0, 0, 1), (-1, 1, 0), (-30, 30), (-70, -30)),
    ("4", (0.2, -0.2, 0), (0.2, -0.2, 0), (0.4, -0.4, 0), (0, 0, 1), (1, 1, 0), (-30, 30), (30, 70)),
]
R = 0.08  # leg cylinder radius (= Ant capsule size)
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "urdf", "spyder_full.urdf")


def cyl(seg, material):
    """A <visual>+<collision> cylinder along `seg`, as a URDF snippet."""
    length = math.dist((0, 0, 0), seg)
    ox, oy, oz = seg[0] / 2, seg[1] / 2, seg[2] / 2
    yaw = math.atan2(seg[1], seg[0])
    origin = f'<origin xyz="{ox:.5f} {oy:.5f} {oz:.5f}" rpy="0 {math.pi/2:.5f} {yaw:.5f}"/>'
    geo = f'<geometry><cylinder radius="{R}" length="{length:.5f}"/></geometry>'
    return (f'    <visual>{origin}{geo}<material name="{material}"/></visual>\n'
            f'    <collision>{origin}{geo}</collision>\n')


def inertial(mass, i):
    return (f'    <inertial><mass value="{mass}"/>'
            f'<inertia ixx="{i}" ixy="0" ixz="0" iyy="{i}" iyz="0" izz="{i}"/></inertial>\n')


def unit(v):
    n = math.dist((0, 0, 0), v)
    return (v[0] / n, v[1] / n, v[2] / n)


def main():
    out = ['<?xml version="1.0"?>\n',
           '<!-- FULL 8-DoF spyder, generated by scripts/make_urdf.py from models/spyder.xml -->\n',
           '<robot name="spyder">\n',
           '  <mujoco><compiler meshdir="../models/assets" discardvisual="false" balanceinertia="true"/></mujoco>\n',
           '  <material name="black"><color rgba="0.07 0.07 0.08 1"/></material>\n',
           '  <material name="tan"><color rgba="0.8 0.6 0.4 1"/></material>\n']

    # base_link = torso: box-mesh skin + sphere collision + the 4 fixed "aux" stubs.
    out.append('  <link name="torso">\n')
    out.append(inertial(0.5, 0.02))
    out.append('    <visual><geometry><mesh filename="torso_shell.stl"/></geometry><material name="black"/></visual>\n')
    out.append('    <collision><geometry><sphere radius="0.25"/></geometry></collision>\n')
    for lid, hip, *_ in LEGS:
        out.append(cyl(hip, "tan"))  # aux stub is rigid to torso -> lives in base_link
    out.append('  </link>\n\n')

    # Each leg: thigh link (hip joint) + shin link (ankle joint).
    for lid, hip, thigh, shin, hax, aax, hrng, arng in LEGS:
        out.append(f'  <link name="thigh_{lid}">\n{inertial(0.1, 0.005)}{cyl(thigh, "tan")}  </link>\n')
        out.append(f'  <link name="shin_{lid}">\n{inertial(0.1, 0.005)}{cyl(shin, "tan")}  </link>\n')
        hx, hy, hz = unit(hax)
        ax, ay, az = unit(aax)
        out.append(
            f'  <joint name="hip_{lid}" type="revolute">\n'
            f'    <parent link="torso"/><child link="thigh_{lid}"/>\n'
            f'    <origin xyz="{hip[0]} {hip[1]} {hip[2]}"/>\n'
            f'    <axis xyz="{hx:.4f} {hy:.4f} {hz:.4f}"/>\n'
            f'    <limit lower="{math.radians(hrng[0]):.4f}" upper="{math.radians(hrng[1]):.4f}" effort="150" velocity="10"/>\n'
            f'  </joint>\n')
        out.append(
            f'  <joint name="ankle_{lid}" type="revolute">\n'
            f'    <parent link="thigh_{lid}"/><child link="shin_{lid}"/>\n'
            f'    <origin xyz="{thigh[0]} {thigh[1]} {thigh[2]}"/>\n'
            f'    <axis xyz="{ax:.4f} {ay:.4f} {az:.4f}"/>\n'
            f'    <limit lower="{math.radians(arng[0]):.4f}" upper="{math.radians(arng[1]):.4f}" effort="150" velocity="10"/>\n'
            f'  </joint>\n\n')

    out.append('</robot>\n')
    with open(OUT, "w") as f:
        f.writelines(out)
    print(f"wrote {OUT}  (1 torso + 8 leg links, 8 hinge joints)")


if __name__ == "__main__":
    main()
